[package]
name = "mfaws"
version = "0.1.0"
edition = "2024"

[dependencies]
cli_select = "0.1.4"
rust-ini = "0.21.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.9.8"
